### ISSUE TITLE
Improve multi-download module selection

### ISSUE THREAD

**Issue by misode** [Gamemode4Dev/gm4.co#28]
```[tasklist]
### Tasks
- [ ] Version does not update when changed via the "All modules" panel
- [ ] Ability to select all modules in a "Browse" category
- [ ] Ability to select all the visible modules in the "All modules" panel after searching
- [ ] Module downloads are not tracked from a multi-download
```
